/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VersoesRouteImport } from './routes/versoes'
import { Route as VBrutalRouteImport } from './routes/v.brutal'
import { Route as VEditorialRouteImport } from './routes/v.editorial'
import { Route as VNoirRouteImport } from './routes/v.noir'
import { Route as VStudioRouteImport } from './routes/v.studio'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VersoesRoute = VersoesRouteImport.update({
  id: '/versoes',
  path: '/versoes',
  getParentRoute: () => rootRouteImport,
} as any)
const VBrutalRoute = VBrutalRouteImport.update({
  id: '/v/brutal',
  path: '/v/brutal',
  getParentRoute: () => rootRouteImport,
} as any)
const VEditorialRoute = VEditorialRouteImport.update({
  id: '/v/editorial',
  path: '/v/editorial',
  getParentRoute: () => rootRouteImport,
} as any)
const VNoirRoute = VNoirRouteImport.update({
  id: '/v/noir',
  path: '/v/noir',
  getParentRoute: () => rootRouteImport,
} as any)
const VStudioRoute = VStudioRouteImport.update({
  id: '/v/studio',
  path: '/v/studio',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/versoes': typeof VersoesRoute
  '/v/brutal': typeof VBrutalRoute
  '/v/editorial': typeof VEditorialRoute
  '/v/noir': typeof VNoirRoute
  '/v/studio': typeof VStudioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/versoes': typeof VersoesRoute
  '/v/brutal': typeof VBrutalRoute
  '/v/editorial': typeof VEditorialRoute
  '/v/noir': typeof VNoirRoute
  '/v/studio': typeof VStudioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/versoes': typeof VersoesRoute
  '/v/brutal': typeof VBrutalRoute
  '/v/editorial': typeof VEditorialRoute
  '/v/noir': typeof VNoirRoute
  '/v/studio': typeof VStudioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/versoes'
    | '/v/brutal'
    | '/v/editorial'
    | '/v/noir'
    | '/v/studio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/versoes'
    | '/v/brutal'
    | '/v/editorial'
    | '/v/noir'
    | '/v/studio'
  id:
    | '__root__'
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/versoes'
    | '/v/brutal'
    | '/v/editorial'
    | '/v/noir'
    | '/v/studio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VersoesRoute: typeof VersoesRoute
  VBrutalRoute: typeof VBrutalRoute
  VEditorialRoute: typeof VEditorialRoute
  VNoirRoute: typeof VNoirRoute
  VStudioRoute: typeof VStudioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/versoes': {
      id: '/versoes'
      path: '/versoes'
      fullPath: '/versoes'
      preLoaderRoute: typeof VersoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/brutal': {
      id: '/v/brutal'
      path: '/v/brutal'
      fullPath: '/v/brutal'
      preLoaderRoute: typeof VBrutalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/editorial': {
      id: '/v/editorial'
      path: '/v/editorial'
      fullPath: '/v/editorial'
      preLoaderRoute: typeof VEditorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/noir': {
      id: '/v/noir'
      path: '/v/noir'
      fullPath: '/v/noir'
      preLoaderRoute: typeof VNoirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/studio': {
      id: '/v/studio'
      path: '/v/studio'
      fullPath: '/v/studio'
      preLoaderRoute: typeof VStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VersoesRoute: VersoesRoute,
  VBrutalRoute: VBrutalRoute,
  VEditorialRoute: VEditorialRoute,
  VNoirRoute: VNoirRoute,
  VStudioRoute: VStudioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
